# ~/.aerospace.toml
# https://github.com/nikitabobko/AeroSpace/blob/main/docs/config-examples/default-config.toml

config-version = 2

start-at-login = true

persistent-workspaces = ["1", "2", "3", "4", "5"]

default-root-container-layout = 'accordion'
accordion-padding = 0

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 2
    inner.vertical =   2
    outer.left =       2
    outer.bottom =     2
    outer.top =        2
    outer.right =      2

[mode.main.binding]

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
