monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_input.usb-Kingston_HyperX_SoloCast-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.volume = 1.0
        node.lock-volume = true
      }
    }
  }
]
