pulse.rules = [
  {
    matches = [
      { application.name = "Chromium input" },
      { application.name = "Discord" },
    ]
    actions = { quirks = [
      block-source-volume
      block-sink-volume
    ]}
  }
]
